loginApp/urls.py
from django.contrib import admin
from django.urls import include, path
from loginApp import views
from django.views.decorators.csrf import csrf_exempt

app_name='loginApp'

urlpatterns = [
    #登录
    path('login/$', views.login_view, name='login_url'),
    #主页
    path('me/<str:submenu_id>/', views.user_view, name='user_url'),
    path('logout/$', views.logout_view, name='logout_url'),
    #注册
    path('signin/$', views.signin_view, name='signin_url'),
    #找回密码
    path('Repassword/',views.Repassword,name='Repassword'),
    path('Repassword2/',views.Repassword2,name='Repassword2'),
    path('sendcode/',views.send_code,name='sendcode'),
    path('testcode/',views.test_code,name='testcode'),
    path('Repassword3/',views.Repassword3,name='Repassword3'),
    path('del_ticket/<str:ticketid>/',views.del_ticket, name='del_ticket_url'),
    path('upload_avatar/', csrf_exempt(views.upload_avatar), name='upload_avatar'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from homeApp.views import home
from productApp.views import product

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', home, name='home'),
    path('about/', include('aboutApp.urls')),
    path('m/',include('productApp.urls')),
    path('u/', include('loginApp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

productApp/urls.py
from django.contrib import admin
from django.urls import include, path
from productApp import views
app_name='productApp'

urlpatterns = [
    path('products/<str:submenu_id>/', views.product, name='product'),
    path('movie/<str:movieid>/', views.movie_view, name='movie_url'),
    # path('order/<str:movieid>/', views.order_view, name='order_url'),
    path('ordering/<str:sessionid>/', views.ordering_view, name='ordering_url'),
    path('ticket/<str:ticketid>/', views.ticket_view, name='ticket_url'),
    path('search/', views.search_view, name='search_url'),
    path('add_fav/<str:movieid>/<str:action>/',views.add_fav_view, name='add_fav_url'),
    path('del_fav/<str:movieid>/',views.del_fav_view, name='del_fav_url'),
]

productApp/models.py
from django.db import models
from django.utils import timezone, datetime_safe
from django.contrib.auth.models import User
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
# 关于电影信息的数据
class kind_base(models.Model):
    kind = models.CharField(max_length=50)
    def __str__(self):
        return self.kind
    class Meta:
        verbose_name = '类型'
        verbose_name_plural = '类型'

class movie_base(models.Model):
    name = models.CharField(max_length=100, verbose_name="名称")
    inform = models.TextField(verbose_name="简介")
    rate = models.FloatField(verbose_name="评分", blank=True, null=True, default=5.0)
    label = models.ManyToManyField(kind_base, verbose_name="标签", null=True, default=None)
    time_publish = models.DateField(max_length=20, default=timezone.now, verbose_name="上映时间")
    views = models.IntegerField(verbose_name="访问量", blank=True, null=True, default=0)
    photo = models.ImageField(upload_to='movie/', blank=True)
    showing = models.BooleanField(default=False, verbose_name="正在上映")

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = '电影'
        verbose_name_plural = '电影'

class review_base(models.Model):
    head = models.CharField(max_length=50, default='标题') #del
    # add time
    # add support
    # add review
    mark = models.FloatField(verbose_name="评分", blank=True, null=True, default=5.0)
    body = models.TextField(max_length=500, verbose_name="内容")
    user = models.ForeignKey(User, verbose_name="用户", related_name="review", null=True, on_delete=models.SET_NULL, default="")
    movie = models.ForeignKey(movie_base, verbose_name="电影", related_name="review", null=True, on_delete=models.CASCADE, default=None)
    time = models.DateTimeField(max_length=20, default=timezone.now, verbose_name="时间")
    def __str__(self):
        return "%s-%s"%(self.movie.name, self.id)
    class Meta:
        verbose_name = '短评'
        verbose_name_plural = '短评'

class picture_base(models.Model):
    name = models.CharField(max_length=50, default='剧照')
    pic = models.ImageField(upload_to='movie/')
    movie=models.ForeignKey(movie_base, verbose_name="电影", related_name="pictures", null=True, on_delete=models.CASCADE, default=None)
    def __str__(self):
        return "%s (%s)"%(self.name, self.id)
    class Meta:
        verbose_name = '剧照'
        verbose_name_plural = '剧照'

class jumbotron_base(models.Model):
    movie = models.ForeignKey(movie_base, verbose_name="电影", related_name="jumbotron", on_delete=models.CASCADE)
    pic = models.ImageField(upload_to='jumbotron/', blank=True, null=True, default=None)
    def __str__(self):
        return "%s (%s)"%(self.movie, self.id)
    class Meta:
        verbose_name = '海报'
        verbose_name_plural = '海报'

# 用户
class user_exp(models.Model):
    photo = ProcessedImageField(upload_to='user/', blank=True, default='static/img/default.jpg',
                            verbose_name='头像', processors=[ResizeToFill(600,600)],)
    favorite = models.ManyToManyField(movie_base, verbose_name="想看", blank=True, null=True, default=None)
    user = models.OneToOneField(User, verbose_name="用户", related_name="other", on_delete=models.CASCADE, default="")

# 关于订票的数据
class hall_base(models.Model):
    name=models.CharField(max_length=100, verbose_name="名称")
    total_seats=models.IntegerField(verbose_name="座位数")

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = '放映厅'
        verbose_name_plural = '放映厅'

class session_base(models.Model):
    movie=models.ForeignKey(movie_base, verbose_name="电影", related_name="session", on_delete=models.PROTECT)
    time=models.DateTimeField(max_length=20, default=timezone.now, verbose_name="时间")
    location=models.ForeignKey(hall_base, verbose_name="厅", on_delete=models.PROTECT, default="")
    ordered_seats=models.IntegerField(verbose_name="已订座位数", blank=True, null=True, default=0)
    charge=models.IntegerField(verbose_name="票价", blank=True, null=True)

    def __str__(self):
        return '%s %s %s' % (self.movie.name, self.location.name, self.time.strftime('%Y/%m/%d %H:%M'))
        # self.time.strftime()
    class Meta:
        verbose_name = '场次'
        verbose_name_plural = '场次'

class ticket_base(models.Model):
    user=models.ForeignKey(User, verbose_name="用户", related_name="tickets", on_delete=models.CASCADE, default="")
    seat=models.IntegerField(verbose_name="座号", blank=True, null=True)
    session=models.ForeignKey(session_base, verbose_name="场次", null=True, on_delete=models.SET_NULL, default=None)
    time_create=models.DateTimeField(max_length=20, default=timezone.now, verbose_name="下单时间")
    STATUS_CHOICES = [(-1,'已取消'), (0,'未生效'), (1,'待核销'), (2,'已核销')]
    status=models.IntegerField(verbose_name="状态", blank=True, null=True, default=0 ,choices=STATUS_CHOICES)
    # -1:已取消 0,'未生效' 1,'已生效'
    
    class Meta:
        verbose_name = '票'
        verbose_name_plural = '票'

productApp/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, redirect, HttpResponse
from .models import movie_base, session_base, ticket_base, User, kind_base, review_base
from django.db.models.functions import Cast
from django.http import JsonResponse
from django.core.paginator import Paginator
# Create your views here.

submenu_dict={'all': '全部电影', 'showing':'正在热映', 'highrate':'高分榜'}

def movie_by_submenu(submenu_id):
    if submenu_id == 'showing':
        return movie_base.objects.filter(showing=True)
    elif submenu_id == 'highrate':
        return movie_base.objects.order_by('-rate')
    else:
        return movie_base.objects.all()

def product(request, submenu_id):
    labels = kind_base.objects.all()
    movies = list(movie_by_submenu(submenu_id))
    filted = False
    # 按标签筛选
    if request.GET and request.GET.getlist('category'):
        filted = True
        category = set(request.GET.getlist('category'))
        movies = [movie for movie in movies if category & set([kind.kind for kind in movie.label.all()])]
    paginator = Paginator(movies, 8)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    return render(request, 'product.html', {
        'active_menu':'product',
        'active_submenu': submenu_id,
        'productName':submenu_dict[submenu_id],
        'movies_paged': page_obj,
        'labels' : labels,
        'filted': filted,
    })

def movie_view(request, movieid):
    movie = get_object_or_404(movie_base, id=movieid)
    sessions = []
    date = None
    dates = None

    # 按date属性分类
    if movie.showing:
        sessions = movie.session.all().order_by('time')
        date_sessions = {}
        for session in sessions:
            time = session.time
            if time:
                date_str = time.strftime("%Y-%m-%d")
                if date_str not in date_sessions:
                    date_sessions[date_str] = []
                date_sessions[date_str].append(session)
        dates=list(date_sessions.keys())
        if 'date' in request.GET:
            date=request.GET['date']
        else:
            date=dates[0]
        sessions=date_sessions[date]

    if request.method == "POST":
        comment = request.POST.get('comment')
        mark = int(request.POST.get('btnradio'))
        if len(comment) < 10:
            error = '评论至少在10字以上'
            return redirect('/m/movie/'+str(movieid)+'?error='+error+'#review_head')
        else:
            #存数据
            len_review = review_base.objects.filter(movie=movie).count()
            movie.rate = movie.rate * len_review/(len_review+1) + mark * 1/(len_review+1)
            movie.save()
            review_base.objects.create(mark=mark,body=comment,movie=movie,user=request.user)
            
            return redirect('/m/movie/'+str(movieid)+'#review_head')
    
    else:
        
        favorite = False
        if request.user.is_authenticated:
            favorite = movie in request.user.other.favorite.all()

        review_list = movie.review.all().order_by('-time')
        paginator = Paginator(review_list, 3)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)

        return render(request, 'movie.html', {
            'movie':movie,
            'pics':movie.pictures.all(),
            'labels':movie.label.all(),
            'reviews_paged':page_obj,
            'current_date':date,
            'dates':dates,
            'sessions': sessions,
            'is_favorite': favorite,
            'rate': "{:.1f}".format(movie.rate)
        })

def ordering_view(request, sessionid):
    session = get_object_or_404(session_base, id=sessionid)
    last_seats = int(session.location.total_seats) - int(session.ordered_seats)
    if request.method == 'POST':
        quantity = int(request.POST.get('quantity'))
        if request.user.is_authenticated == False:
            return redirect('/u/login/$?next=/m/ordering/'+sessionid)
        elif last_seats < quantity :
            return redirect('/m/movie/' + str(session.movie.id) + '?error_order=余票不足' + '#buy_ticket_head')
        else:
            session.ordered_seats += quantity
            session.save()
            for i in range(quantity):
                ticket = ticket_base(session=session, user=request.user, status=1)
                ticket.save()
            return render(request, 'orderSuccess.html', {
                'movie':session.movie,
                'session':session
            })
    else:
        if request.user.is_authenticated == False:
            return redirect('/u/login/$?next=/m/ordering/'+sessionid)
        return render(request, 'ordering.html', {
            'movie':session.movie,
            'session':session
        })

def ticket_view(request, ticketid):
    ticket = get_object_or_404(ticket_base, id=ticketid)
    session = ticket.session
    user = ticket.user
    if request.user != user:
        return redirect('/')
    else:
        return render(request, 'ticket.html', {
            'movie':session.movie,
            'session':session,
            'ticket':ticket
        })

def search_view(request):
    labels = kind_base.objects.all()
    if  request.method == 'GET': 
        q = request.GET.get('s_movie')
        if not q:
            return redirect('/m/products/all') 
        else:
            movies = movie_base.objects.filter(name__icontains=q)

            paginator = Paginator(movies, 8)
            page_number = request.GET.get("page")
            page_obj = paginator.get_page(page_number)

            return render(request, 'product.html', {
                'active_menu':'product',
                'active_submenu': 'search',
                'productName':'搜索结果(共'+ str(len(movies)) +'条)',
                # 'movies': movies,
                'labels' : labels,
                'movies_paged': page_obj,
            })
    else:
        return redirect('/')
    
def add_fav_view(request, movieid, action):
    if request.user.is_authenticated == False:
        return redirect('/u/login/$?next=/m/movie/'+movieid)
    
    movie = get_object_or_404(movie_base, id=movieid)
    if action == 'del':
        if movie in request.user.other.favorite.all():
            request.user.other.favorite.remove(movie)
    elif action == 'add':
        if movie not in request.user.other.favorite.all():
            request.user.other.favorite.add(movie)
    
    return redirect('/m/movie/'+str(movieid))

def del_fav_view(request, movieid):
    movie = get_object_or_404(movie_base, id=movieid)
    if movie in request.user.other.favorite.all():
        request.user.other.favorite.remove(movie)
    return redirect('/u/me/favorites')

productApp/templates/movie.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{movie.name}}-电影{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <!-- pics -->
    <div class="col-md-4">
      <div class="d-flex align-content-center justify-content-center">
        <div class="pic-head"
          style="background-image: url('{{movie.photo.url}}');"></div>
      </div>
    </div>
    <!-- details -->
    <div class="col-md-8">
      <h1 class="mx-2 sub-head">{{movie.name}}</h1>
      <p>
        <span class="m-2 h5">评分：{{rate}}/5.0</span>
        <span class="m-2 h5">年代：{{movie.time_publish.year}}</span>
        {% for label in labels %}<span class="badge text-bg-primary m-1">{{label}}</span>{% endfor %}
      </p>
      <p>{{movie.inform}}</p>

      <div id="simple-list-example">

        {% if is_favorite %}
        <a class="btn btn-danger"
          href="{% url 'productApp:add_fav_url' movie.id 'del' %}"><i
            class="bi bi-heart-fill"></i> 已收藏</a>
        {% else %}
        <a class="btn btn-outline-danger"
          href="{% url 'productApp:add_fav_url' movie.id 'add' %}"><i
            class="bi bi-heart"></i> 想看</a>
        {% endif %}

        {% if movie.showing %}
        <a href="#buy_ticket_head" class="btn btn-primary">购票</a>
        {% else %}
        <a href="#buy_ticket_head" class="btn btn-primary disabled">购票</a>
        {% endif %}
        <a href="#review_head" class="btn btn-success">评价</a>
        <a href="#picture_head" class="btn btn-warning">剧照</a>
      </div>
    </div>
    <div class="row">
      <div class="col-md-9">
        {% if movie.showing %}
        <h2 class="sub-head" id="buy_ticket_head">购票</h2>
        <div class="card">
          <div class="card-header">
            <ul class="nav nav-pills card-header-pills">
              {% for date in dates %}
              <li class="nav-item">
                <a class="nav-link"
                  href="{% url 'productApp:movie_url' movie.id %}?date={{date}}#buy_ticket_head"
                  id="date_{{date}}">{{date}}</a>
              </li>
              {% endfor %}
            </ul>
          </div>
          <div class="card-body">
            <div class="row">
              {% for session in sessions %}
              <!-- 场次 -->
              <div class="col-md-3 col-6">
                <div class="card session-choice">
                  <div class="card-body">
                    <p class="card-text m-0">{{session.location.name}}</p>
                    <p class="card-text m-0">{{session.time.time}}</p>
                    <p class="card-text m-0">{{ session.ordered_seats }}/({{ session.location.total_seats}})个座位</p>
                    <p class="card-text m-0 " style="color: green;">¥{{session.charge}}</p>
                    {% if session.ordered_seats < session.location.total_seats %}
                    <a class="btn btn-success" href="{% url 'productApp:ordering_url' session.id %}">预定</a>
                    {% else %}
                    <a class="btn btn-success disabled" role="button" aria-disabled="true">预定</a>
                    {% endif %}
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>
            <p class="mb-0" style="color:red">{{request.GET.error_order}}</p>
          </div>
        </div>
        {% endif %}

        <h2 class="sub-head" id="review_head">短评</h2>
        <!-- 写评论 -->
        {% if user.is_authenticated %}
        <div class="card mb-2">
          <div class="ch card-header-pills"></div>
          <div class="card-body row">
            <div class="col-md-1 col-2">
              <img class="img-fluid" style="width: 50px; height: 50px; border-radius: 50%; " src="{{request.user.other.photo.url}}" alt="">
            </div>
            <div class="col-md-11 col-10">
              <form action method="post">
                {% csrf_token %}
                <div class="btn-group btn-group-sm mb-1"
                  role="group"
                  aria-label="Basic radio toggle button group">
  
                  <input type="radio" class="btn-check" name="btnradio" id="btnradio1" autocomplete="off" value='1'>
                  <label class="btn btn-outline-danger radio-btn" for="btnradio1">1</label>
  
                  <input type="radio" class="btn-check" name="btnradio" id="btnradio2" autocomplete="off" value='2'>
                  <label class="btn btn-outline-danger radio-btn" for="btnradio2">2</label>
  
                  <input type="radio" class="btn-check" name="btnradio" id="btnradio3" autocomplete="off" value='3'>
                  <label class="btn btn-outline-danger radio-btn" for="btnradio3">3</label>
  
                  <input type="radio" class="btn-check" name="btnradio" id="btnradio4" autocomplete="off" value='4'>
                  <label class="btn btn-outline-danger radio-btn" for="btnradio4">4</label>
  
                  <input type="radio" class="btn-check" name="btnradio" id="btnradio5" autocomplete="off" value='5' checked>
                  <label class="btn btn-outline-danger radio-btn" for="btnradio5">5</label>
                </div>
                <span class="h6 text-danger"> /5.0分</span>
                <textarea class="form-control mb-1" rows="2" type="textarea" id="comment" name="comment" placeholder="发表评论..."></textarea>
                <button class="btn btn-success" type="submit">提交</button>
                <p class="mb-0" style="color:red">{{request.GET.error}}</p>
              </form>
            </div>
          </div>
        </div>
        {% else %}
        <div class="card mb-2">
          <div class="card-body">
            <h5 class="card-text">请登录之后再发表评论。</h5>
          </div>
        </div>
        {% endif %}

        <!-- views -->
        {% for review in reviews_paged %}
        <div class="card mb-1">
          <div class="card-body">
            <div class="d-flex mb-1">
              <img class="img-fluid" style="vertical-align:middle; width: 50px; height: 50px; border-radius: 50%; " src="{{review.user.other.photo.url}}" alt="">
              <div class="mb-1">
                <p class="card-title h5 mx-2">{{review.user}}</p>
                <p class="card-subtitle mx-2 text-muted">{{review.mark}} / 5.0分</p>
                <p class="card-text mx-2 mb-0">{{review.body}}</p>
              </div>
            </div>
          </div>
          <div class="card-footer">
            <p class="text-end mx-2 m-0" style="font-size: small; color: darkgray;">{{review.time |date:'Y-m-d'}} {{review.time |time:'H:i'}}</p>
          </div>
        </div>
        {% endfor %}

        <!-- 分页器 -->
        <nav aria-label="...">
          <ul class="pagination">
            {% if reviews_paged.has_previous %}
            {% if reviews_paged.previous_page_number != 1 %}
            <li class="page-item">
              <a class="page-link" href="?page=1#review_head">1</a>
            </li>
            <li class="page-item disabled">
              <a class="page-link" href>...</a>
            </li>
            {% endif %}
            <li class="page-item">
              <a class="page-link"
                href="?page={{ reviews_paged.previous_page_number }}#review_head">{{ reviews_paged.previous_page_number }}</a>
            </li>
            {% endif %}
            <li class="page-item active" aria-current="page">
              <a class="page-link" href="#review_head">{{ reviews_paged.number }}</a>
            </li>
            {% if reviews_paged.has_next %}
            <li class="page-item">
              <a class="page-link"
                href="?page={{ reviews_paged.next_page_number }}#review_head">{{ reviews_paged.next_page_number }}</a>
            </li>
            {% if reviews_paged.paginator.num_pages != reviews_paged.next_page_number %}
            <li class="page-item disabled">
              <a class="page-link" href>...</a>
            </li>
            <li class="page-item">
              <a class="page-link"
                href="?page={{ reviews_paged.paginator.num_pages }}#review_head">{{ reviews_paged.paginator.num_pages }}</a>
            </li>
            {% endif %}
            {% endif %}
          </ul>
        </nav>
      </div>
      <div class="col-md-3">
        <h2 class="sub-head" id="picture_head">剧照</h2>
        <div id="filmstrip">

          {% for pic in pics %}
          <div class="film">
            <img src="{{pic.pic.url}}" alt="剧照">
          </div>
          {% endfor %}

        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block script %}
<style type="text/css">
    body{
        background-image: linear-gradient(-10deg, rgba(231, 230, 230, 0.2) 0%, rgb(231, 230, 230) 30%), url('{{pics.0.pic.url}}');
    }
</style>

<script type="text/JavaScript">
    $('body').scrollspy({ target: '#simple-list-example' })
</script>

<script type="text/JavaScript">
    $('#date_{{current_date}}').addClass("active");
</script>

<script type="text/JavaScript">
    $('#{{active_submenu}}').addClass("active");
</script>
{% endblock %}

productApp/templates/old_order.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
product
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <!-- pics -->
        <div class="col-md-4">
            <div class="d-flex align-content-center justify-content-center">
                <div class="pic-head" style="background-image:
                    url('{{movie.photo.url}}');">
                </div>
            </div>
        </div>
        <!-- details -->
        <div class="col-md-8">
            <h1 class="sub-head">《{{movie.name}}》的场次</h1>
            <div class="card text-center">
                <div class="card-header">
                    <ul class="nav nav-pills card-header-pills">
                        {% for date in dates %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url
                                'productApp:order_url' movie.id
                                %}?date={{date}}" id="date_{{date}}">{{date}}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="card-body">
                    <div class="row">
                        {% for session in sessions %}
                        <!-- ?? -->
                        <div class="col-md-3 col-6">
                            <div class="card session-choice">
                                <div class="card-body">
                                    <p class="card-text">{{session.time.time}}
                                        {{session.location.name}}厅</p>
                                    <p class="card-text"></p>
                                    <p class="card-text">还剩{{session.last_seats}}个座位</p>
                                    <p class="card-text">¥{{session.charge}}</p>
                                    <a class="btn btn-success" href="{% url 'productApp:ordering_url' session.id %}">预定</a>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div style="margin-top: 20px;">
                <a href="" class="btn btn-danger">想看</a>
                <a href="{% url 'productApp:movie_url' movie.id %}" class="btn
                    btn-primary">评价</a>
                {% if movie.showing %}
                <a href="{% url 'productApp:order_url' movie.id %}" class="btn
                    btn-success">购票</a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-9">

            <h2 class="sub-head">短评</h2>
            <!-- todo:写评论 -->
            {% if user.is_authenticated %}
                <form action="" method="post">
                    {% csrf_token %}
                    <input type="text" id="comment" name="comment" style="width:70%" placeholder="请输入评论">
                    <input type="text" name="mark" width="30%" placeholder="请输入评分(0-5)">
                    <button class="btn btn-success" type="submit">提交</button>
                    <p style="color:red">{{error.comment}}</p>
                </form>
            {% else %}
                <p>请登录之后再发表评论。</p>
            {% endif %}

            {% for review in reviews %}
            <div class="card">
                <div class="card-body">
                    <p class="card-title">{{review.user}}</p>
                    <h6 class="card-subtitle mb-2 text-muted">{{review.mark}}</h6>
                    <p>{{review.body}}</p>
                    <button class="btn btn-light">赞同</button>
                    <button class="btn btn-light">反对</button>
                </div>
            </div>
            {% endfor %}

        </div>
        <div class="col-md-3">
            <h2 class="sub-head">剧照</h2>
                <div id="filmstrip">
                    {% for pic in pics %}
                    <div class="film">
                        <img src="{{pic.pic.url}}" alt="剧照">
                    </div>
                    {% endfor %}
                </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script type="text/JavaScript">
$('#date_{{current_date}}').addClass("active");
</script>
<style type="text/css">
    body{
        background-image: linear-gradient(-10deg, rgba(231, 230, 230, 0.2) 0%, rgb(231, 230, 230) 30%), url('{{pics.0.pic.url}}');    }
</style>
{% endblock %}

productApp/templates/old_test.html
<!DOCTYPE html>
<html>
<head>
    <title>Movie</title>
    <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <label>爱情<input type="checkbox" name="category" value="love"></label>
        <label>科幻<input type="checkbox" name="category" value="science-fiction"></label>
        <label>历史<input type="checkbox" name="category" value="history"></label>
        <button type="submit">筛选</button>
    </form>
    <h2>电影列表</h2>
    <ul id="movies">
    </ul>
    <script>
        $('input[type="checkbox"]').click(function() {
            var categories = [];
            $('input[type="checkbox"]:checked').each(function() {
                categories.push($(this).val());
            });
            $.ajax({
                type: 'POST',
                url: '/movie/',
                data: {
                    'category': categories
                },
                success: function(data) {
                    $('#movies').empty();
                    data.movies.forEach(function(movie) {
                        $('#movies').append('<li>' + movie.name + ' - ' + movie.category + '</li>');
                    });
                }
            });
        });
    </script>
</body>
</html>

productApp/templates/ordersuccess.html
{% extends 'base.html' %}
{% load static %}

{% block title %}预订成功{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="sub-head" id="head">预订成功</h1>
        <div class="row">
            <!-- pics -->
            <div class="col-md-5">
            </div>
            <!-- details -->
            <div class="col-md-6 ">
                <div class="card letter" style="aspect-ratio: 4/3">
                    <div class="d-flex align-content-center justify-content-center m-3" style="height: 100%;">
                        <div class="align-self-center m-3" 
                            style="background-image: url('{{movie.photo.url}}');
                                    width: 35%; aspect-ratio: 1/1;
                                    background-size: cover;
                                    border-radius: 6px;">
                        </div>
                        <div class="align-self-center m-3" 
                            style="width: 200px; height: 200px;
                                background-size: cover;
                                border-radius: 6px;">
                            <p>片名: {{session.movie.name}}</p>
                            <p>时间: {{session.time.year}}年{{session.time.month}}月{{session.time.day}}日 {{session.time.hour}}:{{session.time.minute}}</p>
                            <p>放映厅: {{session.location.name}}</p>
                            <p>票价: {{session.charge}}</p>
                            <p><span id="countdown">3</span>秒后进入我的订单</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
<style type="text/css">
    body{
        background-image:url("{% static '/img/evelope.png' %}");
    }
</style>

<script>
    var timeleft = 2;
    var countdown = setInterval(function(){
      $("#countdown").text(timeleft);
      timeleft--;
      if (timeleft < 0) {
        clearInterval(countdown);
        window.location.href = "{% url 'loginApp:user_url' 'order' %}";
      }
    }, 1000);
</script>
<!-- <script type="text/JavaScript">
    $('#base0').css("background-image", "url('{% static '/img/evelope.png' %}')");
</script> -->
{% endblock %}