loginApp/urls.py
from django.contrib import admin
from django.urls import include, path
from loginApp import views
from django.views.decorators.csrf import csrf_exempt

app_name='loginApp'

urlpatterns = [
    #登录
    path('login/$', views.login_view, name='login_url'),
    #主页
    path('me/<str:submenu_id>/', views.user_view, name='user_url'),
    path('logout/$', views.logout_view, name='logout_url'),
    #注册
    path('signin/$', views.signin_view, name='signin_url'),
    #找回密码
    path('Repassword/',views.Repassword,name='Repassword'),
    path('Repassword2/',views.Repassword2,name='Repassword2'),
    path('sendcode/',views.send_code,name='sendcode'),
    path('testcode/',views.test_code,name='testcode'),
    path('Repassword3/',views.Repassword3,name='Repassword3'),
    path('del_ticket/<str:ticketid>/',views.del_ticket, name='del_ticket_url'),
    path('upload_avatar/', csrf_exempt(views.upload_avatar), name='upload_avatar'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from homeApp.views import home
from productApp.views import product

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', home, name='home'),
    path('about/', include('aboutApp.urls')),
    path('m/',include('productApp.urls')),
    path('u/', include('loginApp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

productApp/urls.py
from django.contrib import admin
from django.urls import include, path
from productApp import views
app_name='productApp'

urlpatterns = [
    path('products/<str:submenu_id>/', views.product, name='product'),
    path('movie/<str:movieid>/', views.movie_view, name='movie_url'),
    # path('order/<str:movieid>/', views.order_view, name='order_url'),
    path('ordering/<str:sessionid>/', views.ordering_view, name='ordering_url'),
    path('ticket/<str:ticketid>/', views.ticket_view, name='ticket_url'),
    path('search/', views.search_view, name='search_url'),
    path('add_fav/<str:movieid>/<str:action>/',views.add_fav_view, name='add_fav_url'),
    path('del_fav/<str:movieid>/',views.del_fav_view, name='del_fav_url'),
]

loginApp/models.py
from django.db import models

# Create your models here.

loginApp/views.py
from django.shortcuts import render, HttpResponseRedirect,HttpResponse,redirect
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import  authenticate, login, logout
from loginApp.utils import main as send
from productApp.models import jumbotron_base, user_exp, ticket_base
from django.http import JsonResponse
from imagekit.models import ProcessedImageField
import re
import json
# Create your views here.

def get_piece_dict():
    piece_dict={'id':[],
                'name':[],
                'intro':[],
                'label':[],
                'year':[],
                'status':[],
                'pics':[]
                }
    for piece in jumbotron_base.objects.all():
        piece_dict['id'].append(piece.movie.id)
        piece_dict['name'].append(piece.movie.name)
        if len(piece.movie.inform) < 200:
            piece_dict['intro'].append(piece.movie.inform)
        else:
            piece_dict['intro'].append(piece.movie.inform[0:200]+'...')
        if piece.pic == '':
            piece_dict['pics'].append(piece.movie.photo.url)
        else:
            piece_dict['pics'].append(piece.pic.url)
    
    len_dict = len(piece_dict['name'])
    return piece_dict, len_dict

#登录
def login_view(request):

    if request.GET.get("next", '') != '' and request.GET.get("next", '') != request.path:
        next=request.GET.get("next", '')
    else:
        next='/'

    if request.method == 'POST':
        piece_dict, len_dict = get_piece_dict()
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user != None:
            login(request, user)
            return HttpResponseRedirect(next)
        else:
            return render(request,'login.html', {
                'piece_dict':json.dumps(piece_dict),
                'len_dict':len_dict,
                'error':'账号或密码错误',
                'submenu':'登录'
            })
    else:
        piece_dict, len_dict = get_piece_dict()
        return render(request, 'login.html', {
            'piece_dict':json.dumps(piece_dict),
            'len_dict':len_dict,
            'submenu':'登录'
            })
    
def logout_view(request):
    logout(request)
    return redirect('/')

#注册
def signin_view(request):

    data_list=User.objects.all()

    if request.method == 'POST':
        username = request.POST["username"]
        email = request.POST["email"]
        password = request.POST["password"]
        password2 = request.POST["password2"]
        errors = {'username':'','password':'','pwd':''}
        flag = True
        if not re.match("^[A-Za-z0-9_]*$", username):
            errors['username'] = '用户名只能由字母,数字和下划线组成'
            flag=False
        else:
            for item in data_list:
                if username == item.username:
                    flag=False
                    errors['username']='此用户名已存在'

        if len(password) > 16 or len(password) < 6:
            flag = False
            errors['password'] = '密码长度应该在6到16位'
        
        if password != password2:
            flag=False
            errors['pwd']='两次密码输入不同'
        
        if not flag:
            piece_dict, len_dict = get_piece_dict()
            return render(request,'login.html',{
                'userid':errors['username'],
                'pwd':errors['password'],
                'piece_dict':json.dumps(piece_dict),
                'len_dict':len_dict,
                'submenu':'注册'
                })
        
        user = User.objects.create_user(username, email, password)
        exp = user_exp.objects.create(user=user)
        exp.save()
        return redirect('/u/login/$')
    else:
        piece_dict, len_dict = get_piece_dict()
        return render(request, 'login.html',{
                'piece_dict':json.dumps(piece_dict),
                'len_dict':len_dict,
                'submenu':'注册'
                })

def Repassword2(request):
    request.session['info'] = {'status':1}
    return render(request,'Repassword2.html')

#验证账号
def Repassword(request):
    errors={'username':''}
    status = request.session.get('info')['status']

    if request.method == 'POST' and status == 1:
        username = request.POST.get('username')
        data_list=User.objects.all()
        if username in [i.username for i in data_list]:
            request.session['info'] = {'username':username,'status':2}
            return render(request,'Repassword.html')
        else:
            errors['username']='用户不存在'
            if username == '':
                errors['username'] = '请输入用户名'
            return render(request,'Repassword2.html',{'errors':errors})
    else:
        return redirect('/u/Repassword2/')

#发送验证码
def send_code(request):
    errors={'email':'', 'code':''}
    status = request.session.get('info')['status']

    if request.method =='POST' and status == 2:
        username=request.session.get('info')['username']
        email=request.POST.get('email')
        data_list=User.objects.all()
        for item in data_list:
            if username == item.username and email == item.email:
                code = send(email)
                new_session = request.session.get('info')
                new_session['code'] = code
                new_session['email'] = email
                new_session['status'] = 3
                request.session['info'] = new_session
                return render(request,'Repassword.html')
        errors['email']='邮箱输入有误'
        return render(request,'Repassword.html',{'errors':errors})
    else:
        return redirect('/u/Repassword2/')

def test_code(request):
    errors={'email':'', 'code':''}
    if request.method =='POST':
        status = request.session.get('info')['status']
        if status == 2:
            errors['email']='请先获取验证码'
            return render(request,'Repassword.html',{'errors':errors})
        elif status == 3:
            code=request.POST.get('code')
            code2=request.session.get('info')['code']
            if code == code2:
                new_session = request.session.get('info')
                new_session['status'] = 4
                request.session['info'] = new_session
                return render(request,'Repassword3.html')
            else:
                errors['code']='验证码输入错误'
                return render(request,'Repassword.html',{'errors':errors,'display':False})
        else:
            print('status: ', status)
            return redirect('/u/Repassword2/')
    else:
        return redirect('/u/Repassword2/')

#重新输入密码
def Repassword3(request):
    status = request.session.get('info')['status']
    if request.method == 'POST' and status == 4:
        errors={'password':''}
        error={'password':''}
        password=request.POST.get('password')
        password2=request.POST.get('password2')
        if len(password) > 16 or len(password) < 6:
            errors['password'] = '密码长度应该在6到16位'
            return render(request,'Repassword3.html',{'errors':errors['password']})
        
        if password != password2:
            error['password']='两次密码输入不同'
            return render(request,'Repassword3.html',{'error':error['password']})
        else:
            user=User.objects.get(username=request.session.get('info')['username'])
            user.set_password(password)
            user.save()
            request.session['info']={}
            return redirect('/u/login/$')

    else:
        return redirect('/u/Repassword2/')
    
    
submenu_dict={'info': '账户信息', 'order':'我的订单', 'favorites':'我的收藏'}
active_status_dict={'1':'added', '-1':'canceled'}

def user_view(request, submenu_id):
    user = get_object_or_404(User, id=request.user.id)

    if submenu_id == 'order':
        
        active_status='1'
        if 'active_status' in request.GET:
            active_status = request.GET['active_status']
            
        tickets=ticket_base.objects.filter(user=user, status=int(active_status))
        return render(request, 'user.html', {
            'user':user,
            'active_submenu': submenu_id,
            'productName':submenu_dict[submenu_id],
            'tickets':tickets,
            'active_status':active_status_dict[active_status]
        })
    else:
        return render(request, 'user.html', {
            'user':user,
            'active_submenu': submenu_id,
            'productName':submenu_dict[submenu_id],
        })

def del_ticket(request, ticketid):
    ticket = ticket_base.objects.get(id=ticketid)
    if request.user == ticket.user:
        ticket.status = -1
        ticket.save()
        return redirect('/u/me/order')
    else:
        return redirect('/u/login/$')
    
def upload_avatar(request):
    # 处理上传图片逻辑
    if request.method == 'POST' and request.FILES.get('avatar'):
        # 保存上传的图片、更新用户头像等操作
        avatar = request.FILES['avatar']
        user = get_object_or_404(User, id=request.user.id)
        user.other.photo.delete()
        user.other.photo = avatar
        user.other.save()
        # print(request.FILES.get('avatar'))
        return JsonResponse({'success': True})
    else:
        return JsonResponse({'success': False})

loginApp/templates/Repassword.html
{% extends 'base.html' %}
{% load static %}

{% block title %}找回密码{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/login_style.css' %}">
<!-- <link rel="stylesheet" href="{% static 'css/login_style.css' %}"> -->
{% endblock css %}
    

{% block content %}
    <div class="container content">
        <div class="row">
            <div class="col-md-4">
                <h2 class="sub-head">找回密码</h2>
                <form action="{% url 'loginApp:sendcode' %}" method="post">
                    {% csrf_token %}
                    <div class="input-group has-validation my-2">
                        <div class="form-floating">
                            <input class="form-control" style="width: 100%;" type="text" id="email" name="email" placeholder="请输入您的账号邮箱" value="{{request.session.info.email}}">
                            <label for="email">邮箱</label>
                        </div>
                        <div class="invalid-feedback" id='errors'>1{{ errors.email }}</div>
                        <button id="sendsms" class="btn btn-primary" type="submit">发送验证码</button>
                    </div>
                    <div id='error' style="color:red">{{ errors.email }}</div>
                </form>
                <form action="{% url 'loginApp:testcode' %}" method="post">
                    {% csrf_token %}
                    <div class="input-group has-validation my-2">
                        <div class="form-floating">
                            <input class="form-control" style="width: 100%;" type="text" id="code" name="code" placeholder="请输入验证码" >
                            <label for="code">验证码</label>
                        </div>
                    </div>
                    <div id='error' style="color:red">{{ errors.code }}</div>
                    <button class="btn btn-primary my-2" type="submit">验证</button>
                </form>       
            </div>
        </div>
    </div>

{% endblock %}

{% block script %}

<script>
    
    $(function(){
        if({{ request.session.info.status }} == '3'){
            var time = 60;
            if(time==60){
               var time1=setInterval(function(){
                   if(time==0){
                       $("#sendsms").html("重新发送");
                       $("#sendsms").removeAttr("disabled");
                       time=60;
                       clearInterval(time1);
                   }else{
                       $("#sendsms").attr("disabled","true");
                       $("#sendsms").html("重新发送("+time+")");
                       time--;
                   }
                }, 1000);
           }
        }
    })
</script>
{% endblock %}

loginApp/templates/Repassword2.html
{% extends 'base.html' %}
{% load static %}

{% block title %}找回密码{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/login_style.css' %}">
{% endblock css %}
    

{% block content %}
    <div class="container content">
        <div class="row">
            <h2 class="sub-head">找回密码</h2>
            <form action="{% url 'loginApp:Repassword' %}" method="post">
                {% csrf_token %}
                <div class="form-floating" id="input-row">
                    <input class="form-control" type="username" id="username" name="username"  placeholder="请输入账号">
                    <label for="username">用户名</label>
                    <div id='error' style="color:red;">{{ errors.username }}</div>
                </div>
                <button id="register" class="btn btn-primary" type="submit"><p>确认</p></button>
            </form>
        </div>
    </div>

{% endblock %}

{% block script %}
{% endblock %}

loginApp/templates/Repassword3.html
{% extends 'base.html' %}
{% load static %}

{% block title %}找回密码{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/login_style.css' %}">
{% endblock css %}
    

{% block content %}
    <div class="container content">
        <div class="row">
            <h2 class="sub-head">找回密码</h2>
                
                <form method="post" action="{% url 'loginApp:Repassword3' %}">
                    {% csrf_token %}
                    <div class="form-floating" id="input-row">
                        <input class="form-control"  type="text" id="username" name="email" placeholder="请输入您的账号邮箱" value="{{request.session.info.email}}" readonly>
                        <label for="username">邮箱</label>
                        <div id='error' style="color:red">{{ error.email }}</div>       
                    </div>

                    <div class="form-floating" id="input-row">
                        <input class="form-control" type="text" id="email" name="number" placeholder="请输入账号" value="{{request.session.info.username}}" readonly>
                        <label for="email">用户名</label>
                        <div id='error' style="color:red">{{ userid }}</div>
                    </div>

                    <div class="form-floating" id="input-row">
                        <input class="form-control" type="password" id="password" name="password"  placeholder="请输入密码">
                        <label for="password">密码</label>
                        <div id='error' style="color:red;">{{ errors }}</div>
                    </div>

                    <div class="form-floating" id="input-row">
                        <input class="form-control" type="password" id="password" name="password2"  placeholder="请确定密码">
                        <label for="password">重复密码</label>
                        <div id='error' style="color:red">{{ error }}</div>
                    </div>
                    
                    <button id="register" class="btn btn-primary" type="submit"><p>确认更改</p></button>
                </form>
        </div>
    </div>

{% endblock %}

{% block script %}
{% endblock %}

loginApp/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}登录{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/login_style.css' %}">
{% endblock css %}

{% block content %}
<div class="container content" style="height: calc(100vh - 70px);">
    <!--  justify-content-around align-items-center -->
    <div class="row" style="height: calc(50% - 200px);"></div>
        <div class="row">
        <div class="m-auto col-12 col-md-6">
            <!-- glass-container -->
            <div id="login_block" class="d-flex row m-0 align-content-center glass-container">
                <div class="d-flex col-12 col-md-4 align-content-center justify-content-center">
                    <h1>{{submenu}}</h1>
                </div>
                <div class="d-flex d-none d-lg-block col-md-1" style="height: 100%;">
                    <div class="vr" style="height: 100%;"></div>
                  </div>
                <div class="d-flex col-12 col-md-6 justify-content-center">
                    <form method="post" action="">
                        {% csrf_token %}

                        {% if submenu == '登录' %}
                        <div class="form-floating" id="input-row">
                            <input class="form-control" style="width: 100%;" type="text" id="username" name="username" placeholder="请输入账号">
                            <label for="username">用户名</label>
                        </div>
                        <div class="form-floating" id="input-row">
                            <input class="form-control" style="width: 100%;" type="password" id="password" name="password"
                                placeholder="请输入密码">
                            <label for="password">密码</label>
                            <div id='error' style="color:red;">{{ error }}</div>
                        </div>
                        <div class="col-12">
                            <button id="register" class="btn btn-primary" type="submit">
                                <p>登录</p>
                            </button>
                            <a href="/u/Repassword2">
                                <button id="register" type="button" class="btn btn-default">找回密码</button>
                            </a>
                        </div>

                        {% else %}

                        <div id="input-row">
                            <input class="form-control" style="width: 100%;" type="text" id="username" name="username"    placeholder="请输入用户名">
                            <div id='error' style="color:red">{{ userid }}</div>
                        </div>
        
                        <div id="input-row">
                            <input class="form-control" style="width: 100%;" type="text" id="email" name="email"     placeholder="请输入您的邮箱">
                        </div>
        
                        <div id="input-row">
                            <input class="form-control" style="width: 100%;" type="password" id="password" name="password"  placeholder="请输入密码">
                            <div id='error' style="color:red;">{{ pwd }}</div>
                        </div>
        
                        <div id="input-row">
                            <input class="form-control" style="width: 100%;" type="password" id="password" name="password2"  placeholder="请确认密码">
                            <div id='error' style="color:red">{{ cfm_pwd }}</div>
                         </div>
                        <button id="register" class="btn btn-primary" type="submit"><p>注册</p></button>
                        
                        {% endif %}
                        
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block script %}
<script type="text/javascript">
    var piece_dict = {{ piece_dict|safe }};
    var index=0;
    var len_index={{ len_dict|safe }};
    var timer = setInterval("qiehuan(1)",6000);

    $('#base0').css("background-image", "url("+piece_dict['pics'][0]+")");
    $('#base1').css("background-image", "url("+piece_dict['pics'][0]+")");

    function timer_stop(){
        clearTimeout(timer);
    }
    function timer_start(){
        timer = setInterval("qiehuan(1)",6000);
    }
    function qiehuan(i){
        timer_stop();
        index=index + i;
        if (index == len_index) {
            index=0;
        } else if (index < 0) {
            index = len_index - 1;
        };
        console.log(index);
        $('#base0').css("background-image", "url("+piece_dict['pics'][index]+")");
        $('#base1').fadeOut(1000, function(){
            $('#base1').css("background-image", "url("+piece_dict['pics'][index]+")");
            $('#base1').fadeIn(1000, timer_start());
        });
    }
</script>
{% endblock %}

loginApp/templates/signin.html
{% extends 'base.html' %}
{% load static %}

{% block title %}注册{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/login_style.css' %}">
{% endblock css %}
    

{% block content %}
    <div class="container content">
        <div class="row">
            <h2>register</h2>
            {% if userNotExist %}
            <div class="row">
                <div class="alert alert-warning col-md-3">用户名或密码错误</div>
            </div>
            {% endif %}
            <form method="post">
                {% csrf_token %}
                <div id="input-row">
                    <label for="username">Username:</label>
                    <input class="form-control"  type="text" id="username" name="username"    placeholder="请输入账号">
                    <div id='error' style="color:red">{{ userid }}</div>
                </div>

                <div id="input-row">
                    <label for="email">email:</label>
                    <input class="form-control" type="text" id="email" name="email"     placeholder="请输入您的邮箱">
                </div>

                <div id="input-row">
                    <label for="password">Password:</label>
                    <input class="form-control" type="password" id="password" name="password"  placeholder="请输入密码">
                    <div id='error' style="color:red;">{{ pwd }}</div>
                </div>

                <div id="input-row">
                    <label for="password">Password:</label>
                    <input class="form-control" type="password" id="password" name="password2"  placeholder="请确定密码">
                    <div id='error' style="color:red">{{ cfm_pwd }}</div>
                 </div>
                
                <button id="register" class="btn btn-primary" type="submit"><p>注册</p></button>
            </form>
        </div>
    </div>

{% endblock %}

{% block script %}
{% endblock %}

loginApp/templates/user.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{productName}}-个人中心{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <h1 class="sub-head">个人中心</h1>
                <div class="model-list">
                    <ul class="list-group">
                        <a href="{% url 'loginApp:user_url' 'info' %}" class="list-group-item" id="info">账户信息</a>
                        <a href="{% url 'loginApp:user_url' 'order' %}" class="list-group-item" id="order">我的订单</a>
                        <a href="{% url 'loginApp:user_url' 'favorites' %}" class="list-group-item" id="favorites">我的收藏</a>
                    </ul>
                </div>
            </div>
            <div class="col-md-9" id="info_content">
                <h1 class="sub-head">{{productName}}</h1>
                <div class="card">
                    <div class="card-body">
                    {% if active_submenu == 'info' %}
                    <div class="d-flex align-items-center ">
                        <div class="mx-3" style=" width: 40vh;">
                            <img class="img-fluid mb-2" style="border-radius: 50%;" src="{{user.other.photo.url}}" alt="">
                        </div>
                        <div class="mx-3" >
                            <h2 class="mb-3">{{user.username}}</h2>
                            <p>邮箱：{{user.email}}</p>
                            <p>
                                <button type="button" class="btn btn-primary mb-1" data-bs-toggle="modal" data-bs-target="#avatarModal">修改头像</button>
                                <a class="btn btn-primary mb-1" href="{% url 'loginApp:Repassword2' %}">更改密码</a>
                            </p>
                        </div>
                    </div>
                    {% endif %}

                    {% if active_submenu == 'order' %}
                        <div class="row">
                            <div class="btn-group">
                                <a href="?active_status=1" id="status_added" class="btn btn-outline-primary">已下单</a>
                                <a href="?active_status=-1" id="status_canceled" class="btn btn-outline-primary">已取消</a>绩
                                设置
                                排行榜
                            </div>
                        </div>
                        {% for ticket in tickets %}
                        <a href="{% url 'productApp:ticket_url' ticket.id %}" class="d-flex my-2" style="width: 100%; text-decoration: none;">
                            <div style="background-image: url('{{ticket.session.movie.photo.url}}');
                                width: 90px; aspect-ratio: 1/1;
                                background-size: cover;
                                border-top-left-radius: 6px;
                                border-bottom-left-radius: 6px;">
                            </div>
                            <div class="card" style="width: 100%; border-bottom-left-radius: 0px; border-top-left-radius: 0px; border-left: 0px;">
                                <div class="card-body">
                                    <h5 class="card-title">{{ticket.session.movie.name}}</h5>
                                    <span class="card-text">{{ticket.session.time.year}}年{{ticket.session.time.month}}月{{ticket.session.time.day}}日</span>
                                    <span>{{ticket.session.time.hour}}:{{ticket.session.time.minute}}</span>
                                    <span class="card-text">{{ticket.session.location}}</span>
                                </div>
                            </div>
                        </a>
                        {% endfor %}
                    {% endif %}

                    {% if active_submenu == 'favorites' %}
                        <div class="row">
                            {% for movie in user.other.favorite.all %}
                            <div class="col-md-4 col-6">
                                <div class="card">
                                    <!-- todo: link -->
                                    <img src="{{movie.photo.url}}" class="card-img-top" alt="" style="height: 200px; width: 100%;">
                                    <div class="card-body">
                                        <h5 class="card-title">{{movie.name}}</h5>
                                        <p class="mb-0">{{movie.rate}}分  {{movie.time_publish.year}} </p>
                                        <p>{% for label in movie.label.all %} {{label}} {% endfor %} {% if movie.showing %}<span class="badge text-bg-danger">正在上映</span>{% endif %}</p>
                                        <a href="{% url 'productApp:movie_url' movie.id %}" class="btn btn-primary">详情</a>
                                        <a href="{% url 'productApp:del_fav_url' movie.id %}" class="btn btn-danger">取消收藏</a>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    {% endif %}
                    </div>
                </div>
            </div>
        </div>    
    </div>
    <!-- else -->
    <!-- endif -->
{% endblock %}

{% block script %}

<script type="text/JavaScript">
    $('#status_{{active_status}}').addClass("active");
</script>
<script type="text/JavaScript">
    $('#{{active_submenu}}').addClass("active");
</script>
<!-- Ajax脚本 -->

<script>
    $(function() {
      // Ajax上传头像
      $('#uploadAvatarBtn').click(function() {
        var formData = new FormData($('#avatarForm')[0]);
        $.ajax({
          url: '{% url "loginApp:upload_avatar" %}',
          type: 'POST',
          data: formData,
          processData: false,
          contentType: false,
          success: function(data) {
            if (data.success) {
              $('#avatarModal').modal('hide');
              alert('头像上传成功！');
              location.reload();
            } else {
              alert('头像上传失败！');
            }
          }
        });
      });
    });
</script>
{% endblock %}